### ISSUE TITLE
cant plot sine curve. 

### ISSUE THREAD

**Issue by kojix2** [oliamb/knnball#3]
Hello

I tried to do Nearest Neighbors regression like this scikit-learn page.
http://scikit-learn.org/stable/auto_examples/neighbors/plot_regression.html

work fine when limitation = 2 or 3. 
But plot looks strange when limitation = 4 or 5

something wrong?
Im sorry for my broken English

``` ruby
require 'nyaplot'
require 'knnball'

X = Array.new(40){|i| i/8.0}
Y = X.map{|x| Math.sin(x) }

T = Array.new(500){|i| i/100.0}

data = X.map.with_index do |f, i|
  {id: i, point: [f]}
end

index = KnnBall.build(data)

[2,3,4,5].each do |n_neighbors|  

  y_ = T.map do |f|
    results = index.nearest([f], limit: n_neighbors)
    sum = results.inject(0) do |memo, result|
      memo + Y[result[:id]]
    end
    sum / n_neighbors.to_f
  end

  # Nyaplot
  plot = Nyaplot::Plot.new
  sc = plot.add(:scatter, X, Y)
  sc.size 20
  plot.add(:line, T, y_)

  plot.export_html "plot_#{n_neighbors}.html"

end
```

n_neighbor = 2
![n_neighbors 2](http://i.imgur.com/d3b0B6i.png)
n_neighbor = 3
![n_neighbors 3](http://i.imgur.com/hu0sN1F.png)
n_neighbor = 4
![n_neighbors 4](http://i.imgur.com/Kkt7zat.png)
n_neighbor = 5
![n_neighbors 5](http://i.imgur.com/JnSv129.png)

**Comment by kojix2** [comment]
It seems that they stop searching potential match before resultsets reached the limit. They move up to their parents and ignore their split_node. 

kdtree.rb
97          if( (coord[dim] - current_node.center[dim]).abs <= best_dist )

kdtree.rb
97          if( (coord[dim] - current_node.center[dim]).abs <= best_dist or results.eligible?(best_dist))

n_neighbor = 5
![n5](http://i.imgur.com/xfNtkke.png)

**Comment by oliamb** [comment]
Hi,

Thanks a lot for the investigation.

Sorry, I'm not maintaining this library a lot those days. Maybe someone in the community might be interested in digging into that from there.

I will be more than happy to consider a pull request and will credit the contribution.

**Comment by kojix2** [comment]
This issue is old and I will close it.

There is a comprehensive machine learning library under development in Ruby called Rumale, which uses NArray.
https://github.com/yoshoku/rumale
